### ISSUE TITLE
KeyError: 'mseF,PSNR(p2point)'

### ISSUE THREAD

**Issue by back95126** [NJUVISION/PCGCv2#7]
When running the test.py

I actually got the **mseF,PSNR (p2point)**

The error message is below :
```
3. Final (symmetric).

   mseF      (p2point): 14991.6

   mseF,PSNR (p2point): 23.2102

   h.        (p2point): 77509

   h.,PSNR   (p2point): 16.0752

Job done! 20.581 seconds elapsed (excluding the time to load the point clouds).

PC Error Metric Time:    29.403 s
Traceback (most recent call last):
  File "/home/benji/anaconda3/envs/DPCGC/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3652, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'mseF,PSNR(p2point)'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 176, in <module>
    all_results = test(filedir, [ckptdir], args.outdir, args.resultdir, scaling_factor=args.scaling_factor,
  File "/home/benji/anaconda3/envs/DPCGC/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "test.py", line 89, in test
    print('D1 PSNR:\t', pc_error_metrics["mseF,PSNR(p2point)"])
  File "/home/benji/anaconda3/envs/DPCGC/lib/python3.8/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/benji/anaconda3/envs/DPCGC/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3654, in get_loc
    raise KeyError(key) from err
KeyError: 'mseF,PSNR(p2point)'
```

**Comment by yydlmzyz** [comment]
Hi, you can try to replace 'mseF,PSNR(p2point)' to 'mseF,PSNR (p2point)', which is to add a space before '(p2point)'.
